package com.example.demo.accessingdata;

import java.io.StringWriter;
import org.slf4j.*;
import org.springframework.http.HttpStatus;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.springframework.http.ResponseEntity;

@Controller // This means that this class is a Controller
@RequestMapping(path="/api/projects") // This means URL's start with /demo (after Application path)
public class ProjectController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private ProjectRepository projectRepository;

  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String requestBody(@RequestBody Project project) {
	  Logger logger = LoggerFactory.getLogger(ProjectController.class);
	  logger.info(project.getImg());
	  logger.info(project.getTitle());
	  logger.info(project.getInfo());
	  logger.info(project.getInfo2());
	  projectRepository.save(project);
	  return "Saved";
  }

  @DeleteMapping(path="/delete/{id}")
  public ResponseEntity<Integer> deletePost(@PathVariable Integer id){
	  Logger logger = LoggerFactory.getLogger(ProjectController.class);
	  try {
		  projectRepository.deleteById(id);
	  }catch(Exception e) {
		  StringWriter sw = new StringWriter();
		  logger.info(sw.toString());
		  return new ResponseEntity<>(HttpStatus.NOT_FOUND);
	  }
	  return new ResponseEntity<>(id, HttpStatus.OK);
  }


  @GetMapping(path="/get")
  public @ResponseBody Iterable<Project> getAllprojects() {
    // This returns a JSON or XML with the users
    return projectRepository.findAll();
  }
}
